### ISSUE TITLE
End Video brightness

### ISSUE THREAD

**Issue by Lukeomichael** [ram-on/SkyTube#443] opened 2019-06-06 15:01 UTC
Once a video ends, the player keeps the screen on. This is not great if you fall asleep. Can you time out after the video ends like Newpipe does?

**Comment by blshkv** [comment] 2019-06-10 23:23
This is a high priority issue for me.  A mobile might get hot because of this bug so it becomes a safety concern

**Comment by gzsombor** [comment] 2019-07-17 07:01
This was actually fixed in #456, it's a duplicate of #350

**Closed by gzsombor** 2019-07-17 07:01 UTC
Labels: enhancement
