### ISSUE TITLE
Download video as audio

### ISSUE THREAD

**Issue by ghost** [ram-on/SkyTube#269] opened 2018-03-15 22:19 UTC
Option to choose whether to download as video or as audio.

**Comment by davidhedlund** [comment] 2018-09-25 06:16
Yeah, like [NewPipe](https://f-droid.org/en/packages/org.schabi.newpipe/).

**Comment by davidhedlund** [comment] 2018-09-25 06:18
By the way, how do I even download videos?

**Comment by ram-on** [comment] 2018-09-25 19:45
@davidhedlund Refer to the below screenshots:

https://i.imgur.com/t8Oganv.jpg

https://i.imgur.com/AizE0wS.jpg

**Comment by davidhedlund** [comment] 2018-09-25 20:07
Thanks but I cannot find the `Download` item on SkyTube Version 2.91 on https://f-droid.org/en/packages/free.rm.skytube.oss/ albet it's text says:

>  download videos,

**Comment by ram-on** [comment] 2018-09-25 20:47
If you are using mobile network such as 4G, then you need to go to the preferences and tick "Allow downloads on mobile network":  https://i.imgur.com/AizE0wS.jpg

**Comment by davidhedlund** [comment] 2018-09-26 01:02
Thanks, but why isn't this enabled by default? Most people will not know about this.

**Comment by ram-on** [comment] 2018-09-26 19:05
> maybe it would be better to keep the menu entry and only disable it, or keep it enabled and show a warning message "you are on mobile and cant download, go to settings and enable it" or something?

Good point.  Will be implemented.

**Comment by davidhedlund** [comment] 2018-09-27 14:19
> Will be implemented.

Should we open a separate issue for this?

**Comment by ram-on** [comment] 2018-09-27 20:44
> Should we open a separate issue for this?

@davidhedlund Yes pls.  I would appreciate that!

**Comment by gzsombor** [comment] 2020-12-31 15:47
Duplicate of #118

**Closed by gzsombor** 2020-12-31 15:47 UTC
Labels: duplicate, enhancement
