### ISSUE TITLE
Server Error issue

### ISSUE THREAD

**Issue by ghost** [ram-on/SkyTube#797] opened 2020-08-13 05:30 UTC
I am using latest 2.973 version of skytube.
When i open app with default settings it gives error as given below:
`Server error: the request cannot be completed because you have completed your <a href="/youtube/v3/getting-started#quota">quota</a>.,
reason: quotaExceeded`

I also tried untick Use newpipe backend from settings but it still gives same error. Screenshot of app is attached below.
![Screenshot_20200813-104006_1](https://user-images.githubusercontent.com/69074626/90097518-9fa2da80-dd25-11ea-83d3-532f1287e1d4.jpg)

**Comment by gzsombor** [comment] 2020-08-13 22:23
The problem is that, there are network calls, which SkyTube could do with the NewPipe API and Google Youtube API, and there are calls, where only Google's API work. For example, listing playlists, and listing featured and most popular videos only works in the later way. So changing the preferred API doesn't modify anything for this.

**Comment by mrpr3s** [comment] 2020-08-28 06:05
So any tweak which can fix this issue ??

Or it will be fixed in future updates of app ?

**Comment by gzsombor** [comment] 2020-08-29 09:52
Until someone implements this with the NewPipe API, the only thing what you can do, is to create a Youtube API key for your own usage - and configure it in SkyTube.

**Comment by gzsombor** [comment] 2020-10-28 08:05
The Playlist listing and the Most popular tab were implemented with NewPipe

**Closed by gzsombor** 2020-10-28 08:05 UTC
Labels: question, youtube-api
