### ISSUE TITLE
Time of the begining of playback

### ISSUE THREAD

**Issue by igor50002** [ram-on/SkyTube#249] opened 2018-02-16 05:16 UTC
Hi, the app is really good!!! But why should we wait for so long time of the start of watching video?

**Comment by ram-on** [comment] 2018-08-19 16:32
@igor50002 This should be resolved now as we are now using the ExoPlayer.  I'm closing this ticket.  Feel free to reopen it if the issue is still persistent.

**Closed by ram-on** 2018-08-19 16:32 UTC
Labels: enhancement
