### ISSUE TITLE
AutoPlay

### ISSUE THREAD

**Issue by joaoemanueljj1** [ram-on/SkyTube#808] opened 2020-09-23 17:51 UTC
I think it should be great if the app could play automatically, including in playlists and normal videos.

#enhacement

**Comment by gzsombor** [comment] 2020-09-24 07:01
Yes, and it looks like a duplicate of or related to https://github.com/ram-on/SkyTube/issues/806 , https://github.com/ram-on/SkyTube/issues/648 and https://github.com/ram-on/SkyTube/issues/329

**Closed by gzsombor** 2020-09-24 07:01 UTC
Labels: duplicate, enhancement
