### ISSUE TITLE
Subscribe buttons dont work correctly

### ISSUE THREAD

**Issue by okan35** [ram-on/SkyTube#682] opened 2020-03-07 20:56 UTC
As title states,when you click subscribe to a channel through search screen,the subscribe buttons on search screen and on channel info dont change into unsubscribe but you can still see the channel in subscribed channels list.

**Comment by gzsombor** [comment] 2020-03-09 00:37
I guess, the NewPipeExtractor returns the channel id as prefixed with 'channel/' after search, but  without on other cases.

**Comment by gzsombor** [comment] 2020-03-15 21:38
Interestingly, I can't reproduce this issue, but I do remember, that I saw it with previous version of the NewPipeExtractor. If you (or anyone else) see it again, we can reopen it.

**Comment by okan35** [comment] 2020-03-15 21:47
I will check if I can fix this because it still happens on my version which is what I pull and build from master branch.

**Comment by okan35** [comment] 2020-03-18 10:41
@gzsombor I found that this issue happens on storyhive channel as you said it returned "channelId/..." I wanted to eliminate this issue as deep as possible so we would not check for channel string if it is correct every time we click on options button.

So I wanted to add a check when we save channel to subscribed channels but I even would like to add this when we get data from newpipe api so we go as deep as possible and other parts of app does not even have to know about this. 

What do you think ?
 this is what I did
https://github.com/okan35/SkyTube/commit/b414b455b40ddab78767ef3337a9661a84a20f32

**Comment by gzsombor** [comment] 2020-03-18 21:28
Interesting. When I try to search to "Safak Salda" I get that channel, and either from the search result, or from opening the channel, I can subscribe successfully.
 What else could be the difference?

**Comment by okan35** [comment] 2020-03-18 21:47
have you checked storyhive channel ? can you please print channel id in these two channels on lines in my commit?

**Comment by gzsombor** [comment] 2020-03-19 08:00
Sorry, you were right, the id contains the channel prefix, but it is seems to working fine. Even if I switch back the Youtube API backend.

**Comment by okan35** [comment] 2020-03-19 08:31
Maybe I couldn't tell you the way to reproduce it correctly but after my changes I don't have any problem, so you think I should push this ?

**Comment by gzsombor** [comment] 2020-03-20 22:37
Hmm, good question. In an ideal world, SkyTube shouldn't manipulate, or convert the ids, and NewPipeExtractor and the Google's API should handle the ids without falling apart, but it's not that world  :) And there are already code, which prefixes the channel id with 'channel/' - in NewPipeService... So I guess, we need to do this conversion. My one ask is to create a separate function for the conversion - maybe in the Utils class -  so later, we can use it in other places too.

**Comment by okan35** [comment] 2020-03-21 09:29
Sure I can add it in the utils class. I mean maybe there is something wrong further deep somewhere as obviously skytube saves the channel id with prefix but when it wants to check it uses channel id without prefix that is why I saw subscribe button for a channel that is already subscribed which gave error at the end. So somewhere a prefix conversion is missing. I do the change and push.

**Comment by gzsombor** [comment] 2020-03-23 21:48
I think, we can close this issue now.

**Closed by gzsombor** 2020-03-23 21:48 UTC
Labels: bug
