### ISSUE TITLE
Can I download audio only?

### ISSUE THREAD

**Issue by 2137mail** [ram-on/SkyTube#409] opened 2019-02-13 10:40 UTC
Like Newpipe (which I just cannot get to work anymore). That would be swell... Thx

**Comment by papel** [comment] 2019-02-15 01:41
That's a good feature. I discovered SkyTube yesterday. I need it for downloading videos into the phone and watch them offline. If I want to listen to songs, I will need only the audio and keep it in m4a rather than mp4.

I've just tried Newpipe and it can download songs, but it doesn't download videos because it's buggy and gets closed whenever I try to download a video.

**Comment by papel** [comment] 2019-02-15 01:49
There are other duplicates (#118 and #269).
I almost created a fourth.

**Comment by 2137mail** [comment] 2019-02-15 09:04
my newpipe just won't download audio anymore.... :( can't figure out why!!



15 Feb 2019, 02:41 by notifications@github.com:

**Comment by ioctl-user** [comment] 2020-12-31 14:14
It's very useful feature.

**Comment by gzsombor** [comment] 2020-12-31 15:46
Duplicate of #118

**Closed by gzsombor** 2020-12-31 15:46 UTC
Labels: duplicate, enhancement
