### ISSUE TITLE
some video of youtube can't play because of exception when decryptSignature using.

### ISSUE THREAD

**Issue by vimio** [ram-on/SkyTube#48] opened 2017-01-09 08:48 UTC
Hello.

When I play the youtube id = kIGK43-Xd8c (https://www.youtube.com/watch?v=kIGK43-Xd8c), I have below exeption errors. Please verify this errors. Thanks.

E/YouTubeVideo: An error has occurred while getting video metadata/streams for video with id=kIGK43-Xd8c
                java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
                    at free.rm.skytube.businessobjects.VideoStream.ParseStreamMetaData.decryptSignature(ParseStreamMetaData.java:229)
                    at free.rm.skytube.businessobjects.VideoStream.ParseStreamMetaData.getStreamMetaDataList(ParseStreamMetaData.java:159)
                    at free.rm.skytube.businessobjects.YouTubeVideo.getVideoStreamList(YouTubeVideo.java:136)
                    at free.rm.skytube.gui.fragments.YouTubePlayerFragment$GetStreamTask.doInBackground(YouTubePlayerFragment.java:396)
                    at free.rm.skytube.gui.fragments.YouTubePlayerFragment$GetStreamTask.doInBackground(YouTubePlayerFragment.java:360)
                    at android.os.AsyncTask$2.call(AsyncTask.java:288)
                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                    at java.lang.Thread.run(Thread.java:818)

**Comment by atomjack** [comment] 2017-01-09 17:54
This is a duplicate of #7.

**Comment by ram-on** [comment] 2017-01-10 20:58
@vimio Which version of SkyTube are you using?

**Comment by ram-on** [comment] 2017-06-16 18:25
This should be resolved due to commit d249e5f848b0338d549df580fb08ea3d69b0b987.

**Closed by ram-on** 2017-06-16 18:25 UTC
