### ISSUE TITLE
Subscription number is always wrong on one channel

### ISSUE THREAD

**Issue by okan35** [ram-on/SkyTube#728] opened 2020-04-03 07:51 UTC
Title basically explains. 

https://ibb.co/RzjHStm

**Comment by gzsombor** [comment] 2020-04-05 22:54
I think, this is a NewPipeExtractor bug - I guess, the problem is that here: https://www.youtube.com/channel/UCC76FBg2d-5NWFD8aK4ql5A/ there is no subscriber count label - or, at least, I can't see it. 
 Maybe, if the reported number is less than 0, we should omit displaying it?

**Comment by okan35** [comment] 2020-04-06 05:43
I guess this channel hid its subscriber number, but on skytube it doesn't show less than 0, it shows 0. Do you see "-1" on logs ? if that is the case then yeah we can hide channels with subscriber number less than 0

**Comment by gzsombor** [comment] 2020-04-06 07:00
It's two problem, one, is that we don't hide that number, even if it returns -1, the other is that NewPipe is not always returning -1.

**Comment by okan35** [comment] 2020-04-06 07:32
Then I guess hide if less than 0 could be solution, because some channels might have 0 subscribers

**Comment by gzsombor** [comment] 2020-04-06 19:32
Yes, I think this is a reasonable solution

**Comment by gzsombor** [comment] 2020-04-08 23:51
Partial fix in #732

**Comment by gzsombor** [comment] 2020-04-13 22:14
Fixed in the forked NewPipeExtractor, which is used in #740

**Closed** 2020-04-13 22:14 UTC
Labels: bug
