### ISSUE TITLE
Disappearing subscriptions

### ISSUE THREAD

**Issue by stemy2** [ram-on/SkyTube#403] opened 2019-01-18 06:01 UTC
Hello,

I have usually 57 channels in my subscription list, but sometimes, this nomber falls to another random number with no reason, it can be 50, 7, 0, and so on. I restored a save where i have all my subscription, but it don't solve anything, the only working solution is restarting my phone.

**Comment by kowith337** [comment] 2019-01-19 02:49
This related to NPE issues, same as https://github.com/TeamNewPipe/NewPipeExtractor/issues/133

Might retrieve the fix from NPE.

**Comment by DrawerButton** [comment] 2019-01-19 05:11
Just happened to me as well. Normally 157 subscriptions. Tried to import a recent backup and it said there was only 50. Imported backup again and it dropped to 40. Tried importing an older backup and it went up to 100, tried again and it said 0. Now I seem to be stuck at 40 no matter what, but they're not always the same 40 on each import.

**Comment by techsoulman** [comment] 2019-01-19 09:59
Getting the same problem, reads 19, 50, 19 etc.
Meant to be 69.

Also it appears not to be loading any new videos into the feed. As well as unable to browse a channel's videos.

**Comment by DrawerButton** [comment] 2019-01-19 16:47
I've been using 2.93 for a while, but the problem just started yesterday. This morning it said pulling new videos from 142 of 140 subscriptions. It seems the subscriptions aren't actually gone, its just failing to pull them randomly. Yesterday it was also occasionally saying it failed to find channel info when trying to play a video, but playback seems fine today.

**Comment by stemy2** [comment] 2019-01-19 17:09
I had this problem in previous versions, but not as often as the current one.

**Comment by gitrdn** [comment] 2019-01-20 07:42
I've had this issue on several versions. What's new now is that, even when my subscriptions list does download properly or even partially,  and I can get my FEED to download properly (sometimes my feed fails, independent of my subscriptions working), I now can click on a subscription but nothing will populate the VIDEOS, PLAYLIST, or ABOUT tabs. NOTHING. 

Any subscriptions are absolutely empty. Sometimes I get the error message "Could not download channel information", but not always.

Plus, many times, when it shows no subscriptions, I can import my backup and it will ask me to restart the app, and there are still no subscriptions. 

Even worse, no searches within Skytube work. Nothing comes up. This whole app is currently a mess for me, which forces me to use NEWPIPE full-time, which I usually only use for the popup and speed features.

I've tried downgrading/upgrading, uninstalling/reinstalling, plenty of rebooting... Unfortunately, it looks like I can't use SKYTUBE at all right now.

**Comment by quantumpacket** [comment] 2019-01-21 00:50
I thought it was just me and kept importing backup. App is practically unusable at the moment. :/

**Comment by ode79** [comment] 2019-01-22 00:13
I am also having worst issues I have had with this app for last few days.

Biggest issue is that click on a subscription and no videos come up in their page. Pull down to reload, reload again and again, and eventually get videos. They usually play fine when I have the list. This seems to be an API/Networking issue?
Same thing with searching sometimes. subscriptions is the worst though.

**Comment by SEC07** [comment] 2019-01-22 02:45
Having the same issue. Random too-low number of subscriptions, not loading any new videos in the feed, and not displaying videos when viewing channels. Ugh, guess I can't get my YouTube fix tonight.

**Comment by quantumpacket** [comment] 2019-01-22 03:38
@ram-on when can we expect a fix for this? NewPipe has already released a fix, so porting over their fix should save time. I've been using it instead, but really like SkyTube's simple UI.

**Comment by jasonmerc** [comment] 2019-01-22 05:19
I can confirm this issue as well, running the latest 2.93 F-Droid version of the app.  I've never noticed this bug in previous versions, ever.

I'm not sure if this is related or not, but sometimes when it's giving me trouble with my sub feed it also has trouble searching for videos as well (I'll enter a search term and nothing will show up).  Force closing the app and reopening it doesn't seem to fix it 100% of the time, but it works sometimes.

Is there any way we can help with the patching process?  I read the people above saying NewPipe already has a fix that can be pulled from, but does the dev think some logs with us having the problem would help with the process anyway?  If so, are there instructions for how to pull logs from this app?

**Comment by ram-on** [comment] 2019-01-22 20:06
This is not an issue of SkyTube, but rather Google fcked up their API for a change :)

**Comment by quantumpacket** [comment] 2019-01-24 04:20
If that's the case then how come I can use NewPipe with no issue whatsoever? They use the same YouTube API right?

**Comment by gzsombor** [comment] 2019-07-16 20:47
I think [this commit](https://github.com/ram-on/SkyTube/commit/c1185bf4314bcd8f093a40bc1272df36aafb33e8) is a fix for the issue. The cause of the problem was, that if SkyTube is started without network access, or Youtube doesn't send correct response for the queries, the initialization code fails in the middle, when it tries to get recent information about the subscribed channel. My fix is to store all the channel information in local database, and if the network query fail, just return the cached values. I'm using this patch for months, and it seems ok, it will be part of the next release.

**Closed** 2019-07-16 20:47 UTC
Labels: bug

**Comment by jasonmerc** [comment] 2019-07-17 19:04
> I think [this commit](https://github.com/ram-on/SkyTube/commit/c1185bf4314bcd8f093a40bc1272df36aafb33e8) is a fix for the issue. The cause of the problem was, that if SkyTube is started without network access, or Youtube doesn't send correct response for the queries, the initialization code fails in the middle, when it tries to get recent information about the subscribed channel. My fix is to store all the channel information in local database, and if the network query fail, just return the cached values. I'm using this patch for months, and it seems ok, it will be part of the next release.
Can't wait for the next release.  Thank you for your contribution!
