### ISSUE TITLE
Crash while opening and presenting feed

### ISSUE THREAD

**Issue by arkdae** [ram-on/SkyTube#852] opened 2020-12-12 21:55 UTC
Today my feed updated as it does, and Skytube crashed. I reopened it, and the twirly displays while it is updating the feed. After some time some videos are displayed and then immediately it crashes again. Every subsequent attempt at opening the program continues to result in the same crash. I'm running version 2.975 (2020-10-31 19:15) on a Lenovo Yoga Book running Android 7.1.1.

**Comment by gzsombor** [comment] 2020-12-13 19:42
Could you please attach your phone to your computer, enable developer debugging, and post if the exception/error message? (Something like `..../android-sdk-linux_x86/platform-tools/adb logcat`, if you are on Linux) It's pretty hard to guess from this, what could went wrong

**Comment by Waltibaba** [comment] 2020-12-17 00:41
Exact same here, crash log available here (auto-uploaded from my custom rom): https://del.dog/afumedarun.txt
. Version is 2.975 from F-Droid, if you need a logcat, I can provide that too - my feed crashes after scrolling just a few videos down.

It might have something to do with subscriptions to deleted channels (https://github.com/ram-on/SkyTube/issues/189) that was supposedly fixed in 2017 but is still broken (I have 6 blank channels subscribed that I can't delete).

**Comment by gzsombor** [comment] 2020-12-31 15:43
Ok, so I had some time to debug this issue a bit, and I think (or hope), that the fix for #833 will solve the problem with videos, where there were no channel stored.
 @Waltibaba - the other issue, what you mention - as far as I understand - is not a critical issue, as it doesn't prevent using the app. If the problem is that, deleted channels still shows up in the sidebar, and you can't open / unsubscribe from them? If yes, please open a separate ticket about it.

**Closed by gzsombor** 2020-12-31 15:43 UTC
Labels: bug
