### ISSUE TITLE
Error 413 when I swipe to see comments

### ISSUE THREAD

**Issue by dschmidt593271** [ram-on/SkyTube#864] opened 2020-12-24 15:33 UTC
Reliably when I swipe from the right edge, I get a toast that says "Error:413 request entity too large" and the new panel says "this video either has no comments or they are turned off".

For the record, I found this which says it's a cookie thing. https://support.mozilla.org/en-US/questions/1180975. So I tried deleting cache and the error persists.

**Comment by gzsombor** [comment] 2020-12-26 21:55
Duplicate of #863

**Closed** 2020-12-26 21:56 UTC
Labels: duplicate
