### ISSUE TITLE
Add Folders or Tags to organize subscriptions

### ISSUE THREAD

**Issue by profucius** [ram-on/SkyTube#840] opened 2020-11-24 20:44 UTC
Managing 100+ subscriptions becomes very chaotic, I suggest adding a feature to add tags to subscriptions, or folders to place them under, so that it is possible to organize them.

**Comment by gzsombor** [comment] 2020-11-29 00:14
Yeah, it's a common requested feature.

**Comment by gzsombor** [comment] 2020-11-29 00:15
Duplicate of #716

**Closed by gzsombor** 2020-11-29 00:15 UTC
Labels: duplicate, enhancement
